services:

  db:
    image: postgres:latest
    container_name: order_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/database.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: order_backend
    restart: always
    ports:
      - "5182:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=order_db;Username=postgres;Password=admin123
      - JwtSettings__Secret=7f809121f64f48868c7e6c496e95c1a7e48b81d7f8a74e5a9c8d3f1e2a0b4c5d
      - JwtSettings__Issuer=OrderManagementAPI
      - JwtSettings__Audience=OrderManagementFrontend
      - JwtSettings__ExpiryMinutes=60
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: order_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
